[theme]
# --- الإعدادات الأساسية للثيم الفاتح ---
base="light"

# استخدام لون الخلفية السكري الدافئ الذي ذكرته
backgroundColor="#FAF9F6"  # <<<--- الخلفية السكرية الدافئة

# لون نص داكن للتباين الجيد
textColor="#262730"

# --- الألوان الأساسية من الشعار ---
# اللون الفوشي الحيوي للأزرار والعناصر البارزة
primaryColor="#EC4BA7"  # <<<--- الفوشي (الوردة)

# اللون الثانوي لخلفيات العناصر مثل رسائل الشات أو الشريط الجانبي
# نستخدم درجة باهتة جداً من البنفسجي الناعم للمسة لونية هادئة
secondaryBackgroundColor="#EDE7F6" # <<<--- درجة باهتة جداً جداً من البنفسجي B59DDF

# --- الخط (اختياري) ---
font="sans serif"